fineanmol/Annoying-submit-button

src/App.css
Fixed the horizontal scroll issue & added cursor pointer for submit button.
=> Minor Fixes

package-lock.json, src/App.css, src/App.js, src/components/Footer/Footer.css, src/components/Footer/Footer.jsx
#9 Improve CSS design of the web-page
For now, I have fixed the design of the footer and added some more styling to its elements to achieve an overall better look.
Some of the changes I made are - 
1. Changed font of "Hacktoberfest 2022" and gave it a cool glitch animation on hover.
[screen-capture.webm](https://user-images.githubusercontent.com/96468766/194540101-370d21f1-b625-4d08-b2a0-51bfdd24839a.webm)
2. Gave hover effects to the social media links as per their respective colour schemes.
[screen-capture (1).webm](https://user-images.githubusercontent.com/96468766/194539238-4182eb87-e3d3-4eb9-9eb3-739aee09916e.webm)
=> Improve CSS design of the web-page #9

src/App.css, src/App.js, src/components/Footer/Footer.css, src/components/Footer/Footer.jsx, src/components/ThemeButton/ThemeButton.css, src/components/ThemeButton/ThemeButton.jsx, src/components/ThemeButton/index.jsx
#14 Improve CSS design of the web-page
Changes made:
1. New button to toggle between dark and bright mode
2. Changed original footer background and font color for both modes
3. Dark mode by default
https://user-images.githubusercontent.com/57314527/194621088-28392223-09ae-4138-bc71-8a38f3ecb3da.mp4
=> Dark and Bright Themes

package-lock.json, src/components/Footer/Footer.css, src/components/Footer/Footer.jsx, yarn.lock
The styling of footer social icons is improved
=> footer improved

src/components/ThemeButton/ThemeButton.css, src/components/ThemeButton/ThemeButton.jsx
#21
Clicking inside the blob was purely intentional but it seems like a bad design. So, I enabled the click on the whole button instead of the blob inside.
=> Toggle on clicking the whole button and not only blob inside

package-lock.json, src/components/ThemeButton/ThemeButton.css, src/components/ThemeButton/ThemeButton.jsx
fix #24 
Added a text indicating the theme and a tooltip to make it self explanatory.
=> Design: Improve Theme toggle button Click

src/components/Footer/Footer.css, src/components/Footer/Footer.jsx
I have open an issue, and this is the solution for that issuse, with issue no #43. Please go through the code and suggest any changes that I have to make before merging it.
=> text align property fixed for mobile design

src/components/Footer/Footer.jsx
Remove hard coded year and added generic copyright year. It will change yearly.
=> Added generic copyright year

src/App.js, yarn.lock
Added smooth transition to submit button when position changes.
=> Added smooth transition to submit button

package-lock.json, src/App.js, src/components/Footer/Footer.css
Submitting under hacktoberfest-2022. Thank you.
=> Fixed email Validation bug, code refactoring and other cosmetic changes.

CONTRIBUTING.md, contributors/contributorsList.js
Hello @fineanmol ,
I have created a contributors folder and contributing.md file which would enable the contributors to read before they could get started in contributing regarding the issue #55 
Looking forward for this PR/MR :smile:
=> Added contributorsfolder and contributing.md - PR hactoberfest2022

src/components/Footer/Footer.jsx
The Youtube Link has been removed
=> footer links fixed

src/components/Footer/Footer.jsx
fix compilation issue <li> tag was never closed
=> feat: fix compilation issue

src/App.js, src/components/Footer/Footer.jsx
=> fix theme not remember bug

src/App.js, src/components/ThemeButton/ThemeButton.jsx
submitting under hacktoberfest.
=> code refactor theme buttons

src/App.js
I've added better accessibility to the form input fields and updated an <a> tag that wasn't being used semantically and causing screen readers to show an error.
Thank you!
=> Tab index for input fields is not correct. Keyboard users can't use this form. #81

src/App.js
Even though the text says that the "Password should be at least 6 characters long", if you entered 6 characters it wouldn't still be available because of the <= conditional
Change the conditional from "lower or equal" to only a "lower than" solves this issue.
=> Fixed min password length

src/App.js
Fixed: A validation error is displayed even when 6 characters are entered
Before
After
=> Fix Password Validation

public/index.html, src/App.css
Hey @fineanmol, I have done some changes. Kindly review them and merge this PR.
=> Changed font style in the project

src/components/ThemeButton/ThemeButton.css, src/components/ThemeButton/ThemeButton.jsx, src/custom-hooks/useMediaQuery.js
I have resolved the issue. Please do add the hactoberfest-accepted tag. Thank you
=> Resolved issue #97 - (Make drop down of color palate for mobile screen size.)

src/components/ThemeButton/ThemeButton.css
Added the zoom-in effect on hovering the theme button.
=> added-hover-effect

src/App.css, src/components/Footer/Footer.css, src/components/ThemeButton/ThemeButton.css
I have added green theme and made some changes in the color codes for a better look of the site.
=> Green Theme

src/components/ThemeButton/ThemeButton.css, src/components/ThemeButton/ThemeButton.jsx
Added the option to choose the green theme.
It could also in the future query the stylesheet dynamically to get the possible themes, perhaps even reading directly the file or something.
Signed-off-by: Daniel Boll <danielboll.academico@gmail.com>
=> feat(contribution): add the option to the previously added green theme

src/App.css, src/components/Footer/Footer.css, src/components/Footer/Footer.jsx
- made the content fit to screen, hence no scroll bar needed
- removed **.** after hacktoberfest text in footer
=> Disabled Scroll

src/App.css, src/components/Footer/Footer.css
~ it looks like the centered form is not centered at all as the footer is floating in both desktop and mobile
~ the parent div is already in flex with the form section stretching, having a fix heights are unnecessary
=> Footer: fixed an issue where footer is floating above form section

src/App.css
=> Button and Footer collapse issue resolved

src/components/Footer/Footer.css
#154 
Instagram button's hover works perfectly like the rest of the hyperlink buttons.
Kindly merge this PR with hacktoberfest-accepted label. Thank You very much!
=> Added hover to Instagram Button

src/App.css
Hey @fineanmol , I have done some changes. Kindly review them and merge this PR.
=> Updated font-size and warning message

src/components/ThemeButton/ThemeButton.css
The green theme button was not visible, so I changed the background color to light green. It just did not blend with the button color
=> Issue with green theme button

src/App.css
=> fixed backgound change bug issue-170

src/App.css, src/App.js, src/components/Footer/Footer.css
=> fixed a bug.

src/components/Footer/Footer.css, src/components/Footer/Footer.jsx
**Description:**
I've made several improvements to the project's footer component, addressing various issues and enhancing its visual appeal.
**Changes Made:**
[0001-Footer-Updated.patch](https://github.com/fineanmol/Annoying-submit-button/files/12908785/0001-Footer-Updated.patch)
[0001-Footer-Updated.patch](https://github.com/fineanmol/Annoying-submit-button/files/12908789/0001-Footer-Updated.patch)
- Replaced static 'Hacktoberfest 2022' with dynamic year display, ensuring an up-to-date footer reflecting the current year.
- Upgraded the footer design, ensuring better visibility and aesthetics.
- Implemented a glitch animation effect on the "Hacktoberfest 2023" text, visible on hover.
- Adjusted the background color, ensuring it doesn't obscure the footer's content.
- Aligned the …
=> Footer Updated

src/App.css
The placeholder for dark theme was not visible so I made some change in css file to change color of placeholder for dark theme
the following issue is solved
=> The placeholder for dark theme was not visible

README.md
used reference style linking for the author links to be used multiple times/declutter( in readme file)
=> Add reference style linking in authors
